### ISSUE TITLE
lxqt-policykit authorization fails with  more than one  sudoer

### ISSUE THREAD

**Issue by bcebul** [lxqt/lxqt-policykit#117] opened 2021-07-15 21:59 UTC
lxqt-policykit authorisation fails with  more than one  sudoer in  the   sudo group
I   confirm  this previously reported bug  description:
https://bugs.launchpad.net/ubuntu/+source/lubuntu-meta/+bug/1828663
In   summary,  an application  launch   from  the  lxqt menu  requiring  pkexec  such  as   Synaptic  or  Gparted causes    a  failure message if  more  than  one   sudoer  exists.  Launching programs   requiring  root   authorisation  from  the terminal   with  sudo  works  as   expected   with   2   sudoers on  the   system.
The   behaviour   persists on  Debian  Bullseye  and  Ubuntu 20.04LTS  with  default  standard newly installed  configurations.  Note   that   sudo  rather  than root authorisation  is  the   default   with  Debian  and   Ubuntu.   Some  users   such  as  me   may  require  more than  one   sudoer on  a  system.
The lxqt behaviour is  not   consistent   with    other   GUI   authorisation  agents   such  as  lxpolkit or  the   Gnome  shell  agent,  which  do  allow   2   sudoers   to  be  present to  work properly.
Altering  the  /etc/xdg/autostart/lxqt-policykit-agent.desktop to  use  lxpolkit  instead of the   lxqt-policykit agent  thusly  results  in  the  expected   proper   behaviour on  the   lxqt desktop:
"
[Desktop Entry]
Type=Application
Name=LXPolkit
TryExec=lxpolkit
Exec=lxpolkit
OnlyShowIn=LXQt;
X-LXQt-Module=true
...
"
Best regards,
Your  bleeding  user

**Comment by bcebul** [comment] 2021-07-16 04:21
See the  other  Ubuntu  report  here:
https://bugs.launchpad.net/ubuntu/+source/lxqt-policykit/+bug/1875774

**Comment by palinek** [comment] 2021-07-16 14:39
What version of lxqt-policykit are you using?
Did you see #105 & #106 (which was released in 0.17.0)?

**Comment by palinek** [comment] 2021-07-16 14:40
For me with 0.17.0, the issue is not reproducible.

**Comment by palinek** [comment] 2021-07-16 14:51
https://packages.ubuntu.com/focal/lxqt-policykit

**Closed** 2021-07-16 14:51 UTC

**Comment by bcebul** [comment] 2021-07-17 02:53
Thanks, Palo.
0.16.0
As  you  note, there  are no  Debian  or  Ubuntu  release packages above
0.16.0  to   test.
Best regards
Bryan
